version: '3.7'
services:
  servicebot:
    image: servicebot/servicebot
    environment:
#      CERTIFICATES: "./ssl/"
      POSTGRES_DB_PORT : "5432"
      POSTGRES_DB_HOST : "db"
      POSTGRES_DB_USER : "servicebot_u"
      POSTGRES_DB_PASSWORD : "secret_doggo"
      POSTGRES_DB_NAME : "sb_db"
#      SMTP_HOST : 'localhost'
#      SMTP_USER : 'postmaster@localhost'
#      SMTP_PASSWORD : 'password'
#      SMTP_PORT : '587'
      PORT : "3000"
    volumes:
      - upload-data:/usr/src/app/uploads
      - environment-file:/usr/src/app/env
#      - /path/to/ssl/certs/on/server:/usr/src/app/ssl
#    links:
#      - db
    networks:
      - backend
    ports:
      - "9024:3000"
      - "4484:3001"
    command: ["sh", "-c", "node /usr/src/app/bin/wait-for-it.js db 5432  && npm run-script start"]

  db:
    image: postgres
    environment:
      POSTGRES_USER : "servicebot_u"
      POSTGRES_PASSWORD : "secret_doggo"
      POSTGRES_DB : "sb_db"
    volumes:
      - db-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    networks:
      - backend
volumes:
  upload-data:
  environment-file:
  db-data:
networks:
  backend:
    driver: overlay
