version: '3.7'
services:
  chatbots:
    image: labsai/eddi:latest
    ports:
      - "8024:7070"
      - "7443:7443"
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: 4.8
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 1G
      EDDI_MEMORY_MAX: 1G
      #EDDI_JAVA_ENV_MONGODB_HOST: mongodb.hosts=mongodb
      EDDI_JAVA_ENV_BASIC_AUTH_ENABLED: webServer.securityHandlerType=basic
    networks:
      - mongo

  mongodb:
    image: mongo
    environment:
      MONGODB_DBNAME=chatbots
    networks:
      - mongo
    volumes:
      - datamongo:/data/db

networks:
  mongo:
    driver: overlay
volumes:
  datamongo:
